### PR TITLE
Improve styles of TinyMCE editor

### PR DESCRIPTION
**Pull request by gauthierm**
https://www.pivotaltracker.com/story/show/88747666

### CODE REVIEW

**Comment by sgarrity** [comment]
No retina images on purpose? (not a blocker)

**Comment by sgarrity** [comment]
Minor visual issue with Firefox: when in SOURCE mode, the height of the textarea is a bit larger than when in VISUAL mode. This covers the active tab blue stripe:


screenshot 2015-09-04 10 25 54

**Comment by gauthierm** [comment]
Curses Firefox!

**Comment by sgarrity** [comment]
> Minor visual issue with Firefox: when in SOURCE mode, the height of the textarea is a bit larger than when in VISUAL mode. This covers the active tab blue stripe:

I can't reproduce this now either. Goblins.

**Comment by sgarrity** [comment]
Tried this and it looks good.

**Pull request merged**
